---

- name: Open firewalld firewall ports
  ansible.posix.firewalld:
    port: "{{ ((fw.port | string) + '/' + fw.proto) if fw.port is defined else omit }}"
    service: "{{ fw.service if fw.service is defined else omit }}"
    immediate: yes
    permanent: yes
    zone: public
    state: enabled
  loop: "{{ firewall_ports }}"
  loop_control:
    loop_var: fw
