---

- name: Open firewalld firewall ports
  firewalld:
    port: "{{ (item.port+'/'+item.proto) if item.port is defined else omit }}"
    service: "{{ item.service if item.service is defined else omit }}"
    immediate: yes
    permanent: yes
    zone: public
    state: enabled
  loop: "{{ firewall_ports }}"
