---

#- name: Populate service facts
#  service_facts:

- name: Get ufw information
  service:
    name: ufw
  register: _ufw

- name: Identifiy firewall active (ufw)
  set_fact:
    firewall_running: ufw
  when:
    - _ufw['status']['ActiveState'] is defined
    - _ufw['status']['ActiveState'] == 'active'
    - firewall_running is undefined

- name: Get nftables information
  service:
    name: nftables
  register: _nftables

- name: Identifiy firewall active (nftables)
  set_fact:
    firewall_running: nftables
  when:
    - _nftables['status']['ActiveState'] is defined
    - _nftables['status']['ActiveState'] == 'active'
    - firewall_running is undefined

- name: Get firewalld information
  service:
    name: firewalld
  register: _firewalld

- name: Identifiy firewall active (firewalld)
  set_fact:
    firewall_running: firewalld
  when:
    - _firewalld['status']['ActiveState'] is defined
    - _firewalld['status']['ActiveState'] == 'active'
    - firewall_running is undefined

- block:

    - name: Search for iptables binary
      command: which iptables
      changed_when: false
      register: _iptables

    - name: Assume iptables when binary is found
      set_fact:
        firewall_running: iptables
      when: _iptables.stdout|length > 0

  when:
    - firewall_running is undefined

- name: Set firewall found
  set_fact:
    firewall_type: "{{ firewall_running | default('unknown') }}"
