---

# - name: Populate service facts
#   service_facts:

- name: Get ufw information
  ansible.builtin.service:
    name: ufw
  register: _ufw

- name: Identifiy firewall active (ufw)
  ansible.builtin.set_fact:
    firewall_running: ufw
  when:
    - _ufw['status']['ActiveState'] is defined
    - _ufw['status']['ActiveState'] == 'active'
    - firewall_running is undefined

- name: Get nftables information
  ansible.builtin.service:
    name: nftables
  register: _nftables

- name: Identifiy firewall active (nftables)
  ansible.builtin.set_fact:
    firewall_running: nftables
  when:
    - _nftables['status']['ActiveState'] is defined
    - _nftables['status']['ActiveState'] == 'active'
    - firewall_running is undefined

- name: Get firewalld information
  ansible.builtin.service:
    name: firewalld
  register: _firewalld

- name: Identifiy firewall active (firewalld)
  ansible.builtin.set_fact:
    firewall_running: firewalld
  when:
    - _firewalld['status']['ActiveState'] is defined
    - _firewalld['status']['ActiveState'] == 'active'
    - firewall_running is undefined

- name: Assume iptables if noting else found
  when:
    - firewall_running is undefined
  block:

    - name: Search for iptables binary
      ansible.builtin.command: which iptables
      changed_when: false
      failed_when: false
      register: _iptables

    - name: Make sure iptables functions
      ansible.builtin.command: iptables -L
      changed_when: false
      register: _iptables_list
      when: _iptables.stdout | length > 0

    - name: Assume iptables when binary is found and functioning
      ansible.builtin.set_fact:
        firewall_running: iptables
      when:
        - _iptables.stdout | length > 0
        - _iptables_list.rc == 0

- name: Set firewall found
  ansible.builtin.set_fact:
    firewall_type: "{{ firewall_running | default('unknown') }}"
