---

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Identifiy firewall active  # noqa jinja[spacing]
  ansible.builtin.set_fact:
    firewall_running: >-
      {%- if ansible_facts.services['ufw'] is defined and ansible_facts.services['ufw']['state'] == 'running' -%}
      ufw
      {%- elif ansible_facts.services['ufw.service'] is defined and ansible_facts.services['ufw.service']['state'] == 'running' -%}
      ufw
      {%- elif ansible_facts.services['nftables'] is defined and ansible_facts.services['nftables']['state'] == 'running' -%}
      nftables
      {%- elif ansible_facts.services['nftables.service'] is defined and ansible_facts.services['nftables.service']['state'] == 'running' -%}
      nftables
      {%- elif ansible_facts.services['firewalld'] is defined and ansible_facts.services['firewalld']['state'] == 'running' -%}
      firewalld
      {%- elif ansible_facts.services['firewalld.service'] is defined and ansible_facts.services['firewalld.service']['state'] == 'running' -%}
      firewalld
      {%- else -%}
      unknown
      {%- endif -%}
  when:
    - firewall_running is undefined

- name: Assume iptables if noting else found
  when:
    - firewall_running == 'NONE'
  block:

    - name: Search for iptables binary
      ansible.builtin.command: which iptables
      changed_when: false
      failed_when: false
      register: _iptables

    - name: Make sure iptables functions
      ansible.builtin.command: iptables -L
      changed_when: false
      register: _iptables_list
      when: _iptables.stdout | length > 0

    - name: Assume iptables when binary is found and functioning
      ansible.builtin.set_fact:
        firewall_running: iptables
      when:
        - _iptables.stdout | length > 0
        - _iptables_list.rc == 0

- name: Set firewall found
  ansible.builtin.set_fact:
    firewall_type: "{{ firewall_running | default('unknown') }}"

- name: Show firewall type
  ansible.builtin.debug:
    var: firewall_type
