---

- name: Open iptables firewall ports  # noqa args[module]
  ansible.builtin.iptables:
    chain: INPUT
    protocol: "{{ fw.proto if fw.proto is defined else omit }}"
    destination_port: "{{ (fw.port | regex_replace('-', ':')) if fw.port is defined else omit }}"
    ctstate: "{{ 'NEW' if fw.proto == 'tcp' else omit }}"
    syn: "{{ 'match' if fw.proto == 'tcp' else omit }}"
    jump: ACCEPT
  loop: "{{ firewall_ports }}"
  loop_control:
    loop_var: fw
