---

- name: Open iptables firewall ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: "{{ item.proto if item.proto is defined else omit }}"
    destination_port: "{{ (item.port|regex_replace('-',':')) if item.port is defined else omit }}"
    ctstate: "{{ 'NEW' if item.proto == 'tcp' else omit }}"
    syn: "{{ 'match' if item.proto == 'tcp' else omit }}"
    jump: ACCEPT
  loop: "{{ firewall_ports }}"
