---

- name: Open firewall ports (Debian)
  ufw:
    rule: allow
    port: "{{ (item.port|regex_replace('-',':')) if item.port is defined else omit }}"
    proto: "{{ item.proto if item.proto is defined else omit }}"
    name: "{{ item.service if item.service is defined else omit }}"
    state: enabled
  loop: "{{ firewall_ports }}"
  when: ansible_os_family == 'Debian'

- name: Open firewall ports (RedHat)
  firewalld:
    port: "{{ (item.port+'/'+item.proto) if item.port is defined else omit }}"
    service: "{{ item.service if item.service is defined else omit }}"
    immediate: yes
    permanent: yes
    zone: public
    state: enabled
  loop: "{{ firewall_ports }}"
  when: ansible_os_family == 'RedHat'
