---

- name: Identify firewall
  ansible.builtin.include_tasks: identify.yml
  when: firewall_type is undefined

- name: Show unsupported message
  ansible.builtin.debug:
    msg: "Unsupported firewall '{{ firewall_running }}' found"
  when: firewall_type in firewall_type_unsupported

- name: Include the appropiate tasks
  ansible.builtin.include_tasks: "{{ firewall_type }}.yml"
  when: firewall_type != 'unknown' and firewall_type not in firewall_type_unsupported
