---

- name: Open UFW firewall ports
  ufw:
    rule: allow
    port: "{{ (item.port|regex_replace('-',':')) if item.port is defined else omit }}"
    proto: "{{ item.proto if item.proto is defined else omit }}"
    name: "{{ item.service if item.service is defined else omit }}"
    state: enabled
  loop: "{{ firewall_ports }}"
