---

- name: Open UFW firewall ports
  community.general.ufw:
    rule: allow
    port: "{{ (fw.port | regex_replace('-', ':')) if fw.port is defined else omit }}"
    proto: "{{ fw.proto if fw.proto is defined else omit }}"
    name: "{{ fw.service if fw.service is defined else omit }}"
    state: enabled
  loop: "{{ firewall_ports }}"
  loop_control:
    loop_var: fw
