---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    firewall_ports: [{'port': '22', 'proto': 'tcp'}, {'port': '53', 'proto': 'udp'}]
  tasks:
    - name: Include role 'ansible-role-firewall'
      ansible.builtin.include_role:
        name: ansible-role-firewall
