---


- name: Converge
  hosts: all
  vars:
    firewall_ports:
      - port: 22
        proto: tcp
      - port: 53
        proto: udp
  tasks:
    - name: Include role 'ansible-role-firewall'
      include_role:
        name: ansible-role-firewall
