# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN sed -i '/^\[main\]$/a sslverify=false' /etc/yum.conf
RUN yum -y install epel-release
RUN yum makecache fast && yum update -y && yum install -y {{ item.packages|join(' ') }} && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all
