# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN sed -i '/^\[main\]$/a sslverify=false' /etc/yum.conf
RUN sed -i '/^\[main\]$/a sslverify=false' /etc/dnf/dnf.conf
RUN dnf update -y && dnf install -y {{ item.packages|join(' ') }} && dnf clean all
