---

- name: Prepare
  hosts: all
  become: yes
  vars:
    proxy_use: false
    proxy_url: "http://127.0.0.1:3128"
  tasks:

    - block:

        - name: Configure APT to use proxy
          copy:
            content: |
              Acquire::http::proxy "{{ proxy_url }}/";
              Acquire::https::proxy "{{ proxy_url }}/";
              Acquire::gtp::proxy "{{ proxy_url }}/";
            dest: /etc/apt/apt.conf.d/80proxy
            owner: root
            group: root
            mode: "0644"
          when: proxy_use|bool

        - name: Update APT cache
          apt:
            update_cache: yes
            cache_valid_time: 1

        - name: Install requirements
          package:
            name:
              - gnupg
            state: present

        - name: Update APT cache
          apt:
            update_cache: yes
            cache_valid_time: 1

      when: ansible_os_family == 'Debian'

    - block:

        - name: Configure YUM to use proxy
          lineinfile:
            path: /etc/yum.conf
            line: "proxy={{ proxy_url }}"
            regexp: "^proxy=.*$"
          when: proxy_use|bool

        - name: Update YUM cache  # noqa command-instead-of-module
          command: yum makecache
          changed_when: false

      when: ansible_os_family == 'RedHat' and (ansible_distribution_major_version|int) < 8

    - block:

        - name: Configure DNF to use proxy
          lineinfile:
            path: /etc/dnf/dnf.conf
            line: "proxy={{ proxy_url }}"
            regexp: "^proxy=.*$"
          when: proxy_use|bool

        - name: Update DNF cache
          dnf:
            update_cache: yes

      when: ansible_os_family == 'RedHat' and (ansible_distribution_major_version|int) >= 8
