---

roles:
  - name: epel
    src: https://github.com/de-it-krachten/ansible-role-epel.git
    version: main
    scm: git
  - name: firewall
    src: https://github.com/de-it-krachten/ansible-role-firewall.git
    version: main
    scm: git
  - name: firewalld
    src: https://github.com/de-it-krachten/ansible-role-firewalld.git
    version: main
    scm: git
  - name: iptables
    src: https://github.com/de-it-krachten/ansible-role-iptables.git
    version: main
    scm: git
  - name: ufw
    src: https://github.com/de-it-krachten/ansible-role-ufw.git
    version: main
    scm: git
